# Generated by Django 4.2 on 2023-04-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Фотография')),
                ('description', models.CharField(max_length=200, verbose_name='Подпись фотограции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Автор')),
            ],
        ),
    ]
