# Generated by Django 4.2 on 2023-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
    ]
