# Generated by Django 4.2 on 2023-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_photomodel_author'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_posts',
            field=models.ManyToManyField(related_name='favorite', to='app.photomodel', verbose_name='Favorite posts'),
        ),
    ]
